[package]
name = "OhnO"
version = "0.1.0"
edition = "2024"

[dependencies]
chromiumoxide = { version = "0.5", features = ["tokio-runtime"], default-features = false }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
